[tool.pytest.ini_options]
# Pytest configuration for Playwright tests
minversion = "6.0"
addopts = "-ra -q --tb=short"
testpaths = [
    "tests",
]
markers = [
    "e2e: marks tests as end-to-end tests",
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

# Playwright specific settings
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]
